name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Tokens
        run: npm run build --workspace=@ignite-ui/tokens

      - name: Build React
        run: npm run build --workspace=@ignite-ui/react

      - name: Remote Caching
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      - name: Build Storybook
        working-directory: ./packages/docs
        run: npm run build-storybook 

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/docs/storybook-static 
          branch: gh-pages 
          clean: true